[workspace]
members = ["crates/busybar", "crates/busylib", "crates/bookdoc"]
resolver = "3"

[workspace.package]
version = "0.0.5"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
license = "Apache-2.0 OR MIT"
edition = "2024"
repository = "https://github.com/foresterre/busybar-rust"
readme = "README.md"

[workspace.dependencies]
# this workspace
busylib = { path = "crates/busylib", version = "0.0.5" }

# external
base64 = "0.23.0"
bytes = "1"
clap = { version = "4.5", features = ["derive", "env", "wrap_help"] }
http = "1"
reqwest = { version = "0.13.4", default-features = false }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1"
storyteller = "2.0.0-beta.1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2.5"
wiremock = "0.6"
