[package]
name = "busybar-render"
description = "Re-encodes BUSY Bar screen frames into more common image formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
rust-version = "1.88"

[dependencies]
base64.workspace = true
crossterm.workspace = true
image.workspace = true
thiserror.workspace = true
